apiVersion: v1
kind: Pod
metadata:
  name: lehenengo-poda
  namespace: nirenamespaces
spec:
  containers:
    - name: lehenengonginx
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: bolumena
    - name: contenido
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "echo Kaixo Tknikatik > /data/index.html && tail -f /dev/null"]
      volumeMounts:
        - mountPath: /data
          name: bolumena
  volumes:
    - name: bolumena
      emptyDir: {}
    - name: bigarrena
      emptyDir: {}