apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= # password
  MYSQL_DATABASE: bXlzcWw= # mysql
  MYSQL_USER: bXlzcWw= # mysql
  MYSQL_PASSWORD: cGFzc3dvcmQ= # password